routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['web']], function() {

    // Login Routes...
        Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
        Route::post('login', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
        Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
    
    // Registration Routes...
        Route::get('register', ['as' => 'register', 'uses' => 'Auth\LoginController@showLoginForm']); //redirect to login/registration page
        Route::post('register', ['as' => 'register.post', 'uses' => 'Auth\RegisterController@register']);
    
    // Password Reset Routes...
        Route::get('password/reset', ['as' => 'password.reset', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
        Route::post('password/email', ['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
        Route::get('password/reset/{token}', ['as' => 'password.reset.token', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
        Route::post('password/reset', ['as' => 'password.reset.post', 'uses' => 'Auth\ResetPasswordController@reset']);

    });

Route::post('/news/like', 'NewsController@like');
Route::post('/settings', 'HomeController@update')->name('settings.update');
Route::post('survey/vote', 'SurveyController@storeHome')->name('survey.storeHome');
Route::post('/news/comment', 'NewsController@comment')->name('news.news_comment');
Route::get('/news/comment', 'NewsController@getComment')->name('news.get_news_comment');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');


/* Admin panel routes */

Route::group(['middleware' => ['auth']], function() {
    
    Route::post('/notification/all', 'notificationController@allNotificationCheck');
    
    Route::get('/', 'HomeController@index')->name('home');
    
    /** Testing Area **/
    Route::get('/test/createUsers', 'Test\databaseSeeder@createUsers');
    Route::get('/test/addFriends', 'Test\databaseSeeder@addFriends');
    Route::post('/notification/read', 'notificationController@read');

    
    /* User Account zone */
    Route::get('/profile/user/{uid}','HomeController@showProfile');
    Route::get('/profile/friends/user/{uid}','HomeController@showFriends');
    Route::get('/profile/settings/notifications', 'HomeController@notifications')->name('profile.notifications');
    Route::get('/profile/settings/personal-informations', 'HomeController@personal_informations')->name('profile.informations');
    Route::get('/profile/settings/friend-requests', 'HomeController@friend_requests')->name('profile.friend_requests');
    Route::get('/profile/settings/change-password', 'HomeController@changePassword')->name('profile.change-password');
    Route::post('/profile/settings/change-password', 'HomeController@updatePassword')->name('profile.change-password');
    Route::get('/profile/messages', 'HomeController@profileMessenger')->name('profile.messages');
    Route::post('/profile/settings/change/user-photo', 'HomeController@changeUserPhoto');
    Route::post('/profile/settings/update/info', 'HomeController@updateInfo')->name('update.userInfo');
    Route::post('/profile/settings/accept/request/{friend}', 'HomeController@acceptFriendship')->name('accept.friend');
    Route::post('/profile/settings/send/request/{friend}', 'HomeController@requestFriendship')->name('accept.friend');
    Route::post('/profile/messenger/get/conversation/{friend}', 'HomeController@getConversation')->name('profile.messenger.get-conversation');
    Route::get('/find/friends','HomeController@findFriends');
    
    
    /* Chat zone */
    Route::post('/message/new/get/{friend_id}', 'chatController@message_new_get');
    Route::post('/chat/user/{uid}', 'chatController@getChat')->name('chat.getChat');
    Route::post('/chat/message/user/{uid}', 'chatController@sendMessage')->name('chat.sendMessage');
    Route::post('/profile/messenger/send/message/{friend}', 'chatController@sendMessage_ProfileMessenger')->name('profile.messenger.send');
    
    Route::get('/search/community','HomeController@search')->name('search.community');
    
    /* Post zone */
    Route::post('/post/like','HomeController@likePost');
    Route::delete('/post/like','HomeController@dislikePost');
    Route::post('/comment/post','HomeController@commentPost');
    Route::post('/create/post', 'HomeController@insertPost')->name('insertPost');
    Route::post('/create/post/preloadImage', 'HomeController@imagePreload');
    Route::post('/status/post','HomeController@postStatus')->name('post.status');
    Route::get('/feed/load-more/{page}', 'HomeController@loadMore');
    
    
    /* Forum zone */
    Route::post('/forum/showpost/{pid}', 'PostController@insertEditReply')->name('forum.insertEditReply');
    Route::get('/forum/create', 'ForumController@showCreate')->name('post.showCreate');
    Route::post('/forum/create', 'ForumController@createPost')->name('category.createPost');
    
    /*------ ADMIN ZONE ------ */
    Route::get('/admin','AdminController@index');

    Route::get('/admin/prize', 'PrizeController@manage')->name('prize.manage');
    Route::post('/admin/prize/insert', 'PrizeController@insertOrUpdate')->name('prize.insertOrUpdate');

    Route::get('/admin/liveEvent', 'LiveEventController@manage')->name('liveEvent.manage');
    Route::post('/admin/liveEvent/insert', 'LiveEventController@insertOrUpdate')->name('liveEvent.insertOrUpdate');

    Route::get('/admin/news', 'NewsController@manage')->name('news.manage');
    Route::post('/admin/news/insert', 'NewsController@insertOrUpdate')->name('news.insertOrUpdate');

    Route::get('admin/survey/create', 'SurveyController@create')->name('survey.adminCreate');
    Route::get('/admin/survey/create/options', 'SurveyController@options')->name('survey.options');
    Route::post('/admin/survey/create', 'SurveyController@insertOrUpdate')->name('survey.insertOrUpdate');

    Route::get('/admin/forum/category', 'ForumCategoryController@manage')->name('category.manage');
    Route::post('/admin/forum/category', 'ForumCategoryController@insertOrUpdate')->name('category.insertOrUpdate');
    Route::get('/admin/forum/category/archived', 'ForumCategoryController@archived')->name('category.archived');
    
    Route::get('/admin/forum/section', 'SectionController@manage')->name('section.manage');
    Route::post('/admin/forum/section', 'SectionController@insertOrUpdate')->name('section.insertOrUpdate');
    Route::get('/admin/forum/section/archived', 'SectionController@archived')->name('section.archived');
    
    Route::get('/admin/forum/post', 'PostController@manage')->name('post.manage');
    Route::post('/admin/forum/post', 'PostController@insertOrUpdate')->name('post.insertOrUpdate');
    Route::get('/admin/forum/post/archived', 'PostController@archived')->name('post.archived');
 
    Route::get('/admin/users', 'UsersController@manage')->name('user.manage');
    Route::post('/admin/users', 'UsersController@insertOrUpdate')->name('user.insertOrUpdate');
    Route::get('/admin/users/archived', 'UsersController@archived')->name('user.archived');
    Route::get('/admin/users/groups', 'UsersController@manageUserGroups')->name('user.groups');
    Route::post('/admin/users/groups', 'UsersController@updateUserGroups');
    Route::get('/admin/user/roleGroup/{$id}','UsersController@getRoleGroup');
    Route::get('/admin/users/friends', 'UsersController@manage')->name('user.friends');

    Route::get('/admin/settings/content', 'SettingsController@show')->name('settings.content');
    Route::post('/admin/settings/content', 'SettingsController@edit')->name('settings.content');

    /* Admin - Manage groups and permissions */
    Route::get('/admin/settings/permissions', 'PermissionController@show')->name('settings.permissions');
    Route::post('/admin/settings/permissions', 'PermissionController@editPermissions')->name('settings.permissions');
    Route::post('/admin/settings/permissions/init', 'PermissionController@init');
    Route::get('/admin/settings/permissions/groups', 'PermissionController@showGroups')->name('settings.manageGroups');
    Route::post('/admin/settings/permissions/groups', 'PermissionController@addGroup')->name('settings.manageGroups');
    Route::put('/admin/settings/permissions/groups', 'PermissionController@editGroup')->name('settings.editGroups');
    Route::delete('/admin/settings/permissions/groups/{groupId}', 'PermissionController@removeGroup')->name('settings.removeGroups');


});    

Route::resource('survey', 'SurveyController');
Route::resource('news', 'NewsController');
Route::resource('liveEvent','LiveEventController');
Route::resource('prize', 'PrizeController');
    

/* End Admin Panel routes */



Route::get('/search', 'ForumController@search')->name('forum.search');
Route::get('/forum', 'ForumController@index')->name('forum.index');
Route::get('/forum/category/{cat}', 'ForumCategoryController@show')->name('forum.showCategory');
Route::get('/forum/showpost/{pid}', 'PostController@show')->name('forum.showPost');



/*
Route::get('/news/insert', function() {
    return view('news/insert');
});

Route::post('/news/insert', function() {
    return view('news/insert');
});
*/

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    protected $table = 'community_news';

    protected $fillable = ['title', 'content', 'id', 'reward', 'image'];

}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\News;
use App\NewsLike;
use App\NewsComment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Session;
use DB;
use Auth;
use Illuminate\Support\Facades\Storage;
use App\Http\Middleware\UserGroupCheck;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $news = News::all();

        return view('news/index')->with(['news'=>$news]);
    }

    public function insertOrUpdate(Request $request)
    {
        //checking permissions
        if(!UserGroupCheck::check(['ManageNews'])){
            return view("errors.no-permission");
        }
       
        if (null !== $request->file('image')) {
            $path = Storage::put('public/images', $request->file('image'));
            // cause of a problem storing images we have to cut off the prefix "public/" from the path
            $path = substr($path, 7);
        }
    
        $new = News::updateOrCreate(
            ['id' => $request->input('news_id')],
            ['content' => $request->input('content'),
            'title' => $request->input('title')]
        );

        if (isset($path)) {
            News::updateOrCreate(
                ['id' => $new->id],
                ['image' => $path]);
        }

        $news = News::orderBy('id','desc')->get();

        return view('admin.news.admin-news',compact('news'));
    }

    public function manage()
    {
        //checking permissions
        if(!UserGroupCheck::check(['ManageNews'])){
            return view("errors.no-permission");
        }

        $news = News::orderBy('id','desc')->get();
        return view('admin.news.admin-news',compact('news'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('news/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $news = new News;
        $news->title = $request->input('title');
        $news->content = $request->input('content');
        
        
        $news->save();

        return Redirect::to('news');
    }

    public function comment(Request $request) {
        $news_comment = new NewsComment;
        $news_comment->user_id = $request->input('user_id');
        $news_comment->news_id = $request->input('news_id');
        $news_comment->body = $request->input('body');
        $news_comment->save();
    }

    public function getComment(Request $request) {
        $news_comment = DB::table('news_comments')
        ->join('users','news_comments.user_id','=','users.id')
        ->where('news_comments.news_id',$request->input('news_id'))
        ->get();;
        return response()->json(['news_comments'=>$news_comment]);
    }

    public function like(Request $request) {
        $PRESSED = "0";
        $NOT_PRESSED = "1";
        if ($request->input('like') !== $PRESSED) {
            $news_like = DB::table('news_likes')
            ->where('user_id', '=', $request->input('user_id'))
            ->where('news_id', '=', $request->input('news_id'));
            
            $news_like->delete();
        }
        else 
        {
            $news_like = new NewsLike;
            $news_like->news_id = $request->input('news_id');
            $news_like->user_id = $request->input('user_id');
            $news_like->save();
        }
    }


    /**
     * Display the specified resource.
     *
     * @param  \App\News  $news
     * @return \Illuminate\Http\Response
     */
    public function show($news_id)
    {
        $news = DB::select("SELECT
                        *,
                        (CASE WHEN :user_id IN (SELECT b.user_id
                        FROM news_likes b
                        WHERE a.id = b.news_id)
                            THEN 0
                        ELSE 1 END)             AS liked,
                        (SELECT count(b.id)
                        FROM news_likes b
                        WHERE a.id = b.news_id) AS likes
                        FROM news a
                        WHERE a.id = :news_id;",
                 ['news_id' => $news_id, 'user_id' => Auth::user()->id]);

        $comments = DB::select("SELECT a.*, COUNT(b.id) AS comment_likes
            FROM news_comments a
            LEFT JOIN news_comment_likes b ON a.id = b.news_comments_id
            WHERE a.news_id = :news_id
            GROUP BY a.id;", ['news_id' => $news_id]);

        //dd($news);
            
        return view('news/show',compact('news', 'comments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\News  $news
     * @return \Illuminate\Http\Response
     */
    public function edit(News $news)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\News  $news
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, News $news)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\News  $news
     * @return \Illuminate\Http\Response
     */
    public function destroy(News $news)
    {
        //
    }
}

resources/views/news/create.blade.php
@extends('layouts.app')

@section('content')

<form method="POST" action="{{ route('news.store') }}" style="margin-top: 12%">
  {{ csrf_field() }}
  <div class="bootstrap-iso">
    <div class="container-fluid">
     <div class="row">
      <div class="col-md-6 col-sm-6 col-xs-12">
       <form method="post">
        <div class="form-group ">
      
         <input class="form-control" id="title" name="title" placeholder="Insert Title" type="text"/>
        </div>
        <div class="form-group ">

         <textarea class="form-control" cols="40" id="content" name="content" rows="10"></textarea>
        </div>
        <div class="form-group">
         <div>
          <button class="btn btn-primary " name="submit" type="submit">
           Inserisci
          </button>
         </div>
        </div>
       </form>
      </div>
     </div>
    </div>
   </div>

@endsection

resources/views/news/edit.blade.php
@extends('layouts.app')

@section('content')

<form method="POST" action="{{ route('') }}">
  <div class="form-group">
    <label for="exampleFormControlInput1">Email address</label>
    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect1">Example select</label>
    <select class="form-control" id="exampleFormControlSelect1">
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option>
    </select>
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect2">Example multiple select</label>
    <select multiple class="form-control" id="exampleFormControlSelect2">
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option>
    </select>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Example textarea</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
  </div>
  <button type="submit" action="" class="btn btn-default">Submit</button>
</form>

@endsection

resources/views/news/index.blade.php
@extends('layouts.app')

@section('content')

    @if ($news)
        @foreach ($news as $n)
            <ul>   
                <li>{{ $n->title }} </li>
                <li>{{ $n->description }} </li>
         </ul>
        @endforeach
    @endif

    
@endsection

resources/views/news/news-block.blade.php
@section('news-block')
    <table class="table table-striped">
        <tbody>
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Body</th>
                </tr>
            </thead>
    @if ($news)
        @foreach ($news as $n)
            <tr class='clickable-row' data-href='news/{{$n->id}}' style="cursor: pointer;">
                <th scope="row">{{$n->title}}</th>
                <td>{{$n->content}}</td>
            </tr>
        @endforeach
    @endif        
        </tbody>
    </table>

    <script>
    jQuery(document).ready(function($) {
    $(".clickable-row").click(function() {
        window.location = $(this).data("href");
    });
});
    </script>

@endsection

resources/views/news/show.blade.php
@extends('layouts.app')

@section('content')

@if (count($news) >0)
<h2>News </h2>
  <h3>{{ $news[0]->title }} </h2>
  <p>{{ $news[0]->content }}</p>
  <p>likes:  {{ $news[0]->likes }}</p>
  <button id="news_like" value="{{$news[0]->liked}}"> Press to like</button>
@if ($comments)
<h2>Commenti </h2>
@foreach ($comments as $n)
  <ul id="comments_list">   
    <li>{{ $n->body }} </li>
  </ul>
@endforeach

<div> 
      <label>Inserisci commento ... </label>
      <input id="body" type="text">  
</div>

<button type="submit" id="comment_button" class="btn btn-default">Save</button>

@endif
@endif

<script>
  const PRESSED = 1;
  const NOT_PRESSED = 0;

	$('#comment_button').on('click', function () {
		var comment = $('#body').val();
    $.ajax({
      url : "comment",
      type : "POST",
      data: {'body': comment, 'user_id': {{Auth::user()->id}}, 'news_id': {{$news[0]->id}} },
      headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
      },
      cache : false,
      success: function(response) {     
        $('#comment_button').val("");
        $('#comments_list').append("<li>"+ comment +"</li>")
      },
      error: function(response) {
        alert('An error occurred.');
      }
      });
   	});
	
    $('#news_like').on('click', function () {
      var new_value = $('#news_like').val() == PRESSED ? NOT_PRESSED : PRESSED;
      var value = $('#news_like').val() == PRESSED ? PRESSED : NOT_PRESSED;
      console.log(value)
      $.ajax({
        url : "like",
        type : "POST",
        data: {'like': value, 'user_id': {{Auth::user()->id}}, 'news_id': {{$news[0]->id}} },
        headers: {
          'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        },
        cache : false,
        success: function(response) {
          $('#news_like').val(new_value);
        },
        error: function(response) {
          alert('An error occurred.');
        }
        });
   	});

</script>

@endsection